### ISSUE TITLE
Installation Error  Class "GeoSot\FilamentEnvEditor\FilamentLEnvEditorPlugin" not found

### ISSUE THREAD

**Issue by momostafa** [GeoSot/filament-env-editor#1]
Hi thanks for the free plugin I got  below error after registering the plugin 

PHP 8.2.16
Laravel 11.4.0
Filament 3.x.x latest version 

` Error 

  Class "GeoSot\FilamentEnvEditor\FilamentLEnvEditorPlugin" not found

  at app/Providers/Filament/AdminPanelProvider.php:57
     53▕                        )
     54▕             ->plugin(\TomatoPHP\FilamentSettingsHub\FilamentSettingsHubPlugin::make())
     55▕             ->plugin(\TomatoPHP\FilamentAlerts\FilamentAlertsPlugin::make())  
     56▕             ->plugin(\BezhanSalleh\FilamentShield\FilamentShieldPlugin::make())
  ➜  57▕             ->plugin(\GeoSot\FilamentEnvEditor\FilamentLEnvEditorPlugin::make()
     58▕                     ->navigationGroup('System Tools')
     59▕                     ->navigationLabel('My Env')
     60▕                     ->navigationIcon('heroicon-o-cog-8-tooth')
     61▕                     ->navigationSort(1)

      +35 vendor frames 

  36  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(Filament\FilamentServiceProvider))
      +5 vendor frames 

  42  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))`

**Comment by GeoSot** [comment]
Apologies for my delay. Did you find a solution on our problem?

**Comment by momostafa** [comment]
Hi, unfortunately I couldn't resolve the problem myself I am fairly new to Laravel

**Comment by aeq-dev** [comment]
It's a typo ! 
Just edit it as this : 

`use GeoSot\FilamentEnvEditor\FilamentEnvEditorPlugin;`

```
FilamentEnvEditorPlugin::make()
                        ->navigationGroup('System Tools')
                        ->navigationLabel('My Env')
                        ->navigationIcon('heroicon-o-cog-8-tooth')
                        ->navigationSort(1)
                        ->slug('env-editor')
```

**Comment by GeoSot** [comment]
thanks a lot @aeq-dev

**Comment by aeq-dev** [comment]
You're welcome @GeoSot 
Another small issue, you need to add this :    `public array $data = [];` in `ViewEnv` page

**Comment by aeq-dev** [comment]
Also a last typo when we use a custom page :D 
`->viewPage(CustomEnvPage::class)`

**Comment by GeoSot** [comment]
> You're welcome @GeoSot Another small issue, you need to add this : `public array $data = [];` in `ViewEnv` page

Can you please explain me. I am not sure of this

**Comment by GeoSot** [comment]
@aeq-dev I applied your suggestion in main branch.  I would appreciate your confirmation on this
