### ISSUE TITLE
Undefined method 'viewLog'

### ISSUE THREAD

**Issue by ELMEHDI2025** [GeoSot/filament-env-editor#3]
The outcomes of following the instructions provided did not match what was anticipated. The following error message was received:

Call to undefined method GeoSot\FilamentEnvEditor\FilamentEnvEditorPlugin::viewLog()

![Sans titre](https://github.com/GeoSot/filament-env-editor/assets/82848859/35153593-11d7-41da-9da7-3ee50361d24c)

**Comment by GeoSot** [comment]
Please try `viewPage`

**Comment by ELMEHDI2025** [comment]
That did indeed work. Thank's
